### ISSUE TITLE
Question about project

### ISSUE THREAD

**Issue by termermc** [robertorotten/nimonero#1]
I've been looking for a Nim Monero library for a little while and just came across this. Is this something you're planning on continuing? If you have a plan for this and want some help, I'd be happy to contribute.

**Comment by ment1na** [comment]
hey, this is my second account, yes, i plan on continuing this but i currently haven't been uploading files as i have been working on it locally.
i plan on releasing a small beta in a few weeks.

**Comment by termermc** [comment]
Cool, thanks
